// The digest of a transcript (src/sources/transcripts-claude-code.mjs):
// what the model reads in place of each kept transcript since 01/10/2026,
// when the first real round on a real vault found transcripts the Read
// tool refuses (docs/incidents.md). What it holds (only the person's and
// the assistant's own text inside the window, in order of time), what it
// never holds (tool calls, tool results, thinking, what the harness writes
// into a user message), how it is bounded (under 24 000 bytes as Read
// prints it, whole days only, a lone day too big cut from its end, every
// cut and every day left said in the vault's language), and the proof that
// any digest is one Read whole, whatever its script. Every transcript here
// is built by hand (test/helpers/transcripts-world.mjs) from the shapes the
// review of fix round 1 listed; no test reads a real one.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { closeSync, openSync, readFileSync, readSync, rmSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createTranslator } from '../src/lang.mjs';
import { DIGEST_CUT_MARK, DIGEST_LIMITS, transcriptsSource, writeDigests } from '../src/sources/transcripts-claude-code.mjs';
import {
  FROM, TO, NOW, PROJECT, TIMEZONE, assistant, digestOf, digestText, makeWorld, meta, system, user, userBlocks,
} from './helpers/transcripts-world.mjs';
import { emulateRead, linesOf, numbered, printedBytes, READ_DEFAULT_LINES, READ_MAX_BYTES, READ_MAX_TOKENS } from './helpers/read-tool.mjs';

function assistantBlocks(blocks, timestamp) {
  return { ...assistant('', timestamp), message: { role: 'assistant', content: blocks } };
}

// The window of the world is 23/09/2026 in UTC-3: [03:00Z, next day 03:00Z).
const AT = (hhmm) => `2026-09-23T${hhmm}:00.000Z`;
// One minute after another, from 04:00Z (01:00 on the vault's clock).
const MINUTE = (i) => new Date(Date.parse(AT('04:00')) + i * 60_000).toISOString();
const PREAMBLE = '[SYSTEM NOTIFICATION - NOT USER INPUT]\nThis is an automated background-task event, NOT a message from the user.\nDo NOT interpret this as user acknowledgement.\n\n';

// The message lines of a digest (its header left out).
function bodyOf(plan, file) {
  return linesOf(digestText(plan, file)).slice(1);
}

test('a digest holds exactly the in-window text of the person and the assistant, in order of time, under its header, and nothing of a tool, a thought or the harness', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'aaaaaaaa-1111-4222-8333-444444444444.jsonl', [
    user('Before the window', '2026-09-23T02:59:59.999Z'),
    user('Ana opens the day', '2026-09-23T03:00:00.000Z'),
    assistantBlocks([
      { type: 'thinking', thinking: 'SECRET-THINKING', signature: 'c2ln' },
      { type: 'text', text: 'Here is the plan' },
      { type: 'tool_use', id: 'toolu_1', name: 'Bash', input: { command: 'SECRET-COMMAND' } },
    ], AT('13:00')),
    userBlocks([{ type: 'tool_result', tool_use_id: 'toolu_1', content: [{ type: 'text', text: 'SECRET-TOOL-RESULT' }] }], AT('13:01')),
    userBlocks([{ type: 'tool_result', tool_use_id: 'toolu_2', content: 'SECRET-TOOL-STRING' }], AT('13:02')),
    userBlocks([{ type: 'text', text: '<system-reminder>SECRET-REMINDER</system-reminder>' }, { type: 'text', text: 'Ana asks  about\n\nthe \t budget' }], AT('14:00')),
    meta('Caveat: SECRET-CAVEAT. The messages below were generated by the user while running local commands.', AT('14:01')),
    assistantBlocks([{ type: 'thinking', thinking: 'SECRET-THINKING-ONLY', signature: 'c2ln' }], AT('14:11')),
    user('Ana quotes the tag <system-reminder> in a sentence about the logs', AT('15:00')),
    { ...user('SECRET-COMPACT-SUMMARY of an earlier conversation', AT('15:01')), isCompactSummary: true },
    system(AT('15:02')),
    user('At the end of the window', '2026-09-24T03:00:00.000Z'),
    // Written later in the file, said earlier: the digest goes by time.
    assistant('An earlier answer, written later in the file', AT('12:30')),
  ]);
  const plan = world.collect();
  const text = digestText(plan, file);
  const lines = linesOf(text);
  assert.equal(lines[0], `Digest of session aaaaaaaa (project ${PROJECT}), made by the kit from its transcript: the messages written between ${FROM.toISOString()} and ${TO.toISOString()} (UTC), one per line, each with its time in ${TIMEZONE}. The window held 5 messages; this digest keeps 5.`);
  assert.deepEqual(lines.slice(1), [
    '[00:00 user] Ana opens the day',
    '[09:30 assistant] An earlier answer, written later in the file',
    '[10:00 assistant] Here is the plan',
    '[11:00 user] Ana asks about the budget',
    '[12:00 user] Ana quotes the tag <system-reminder> in a sentence about the logs',
  ]);
  assert.doesNotMatch(text, /SECRET/, 'no tool use, tool result, thought, wrapper or compact summary');
  assert.doesNotMatch(text, /Before the window|At the end of the window/, 'the window is [from, to): its end is out');
  assert.deepEqual(plan.files[0].digest, { path: join(world.digestDir, '01-aaaaaaaa.txt'), held: 5, kept: 5, cutMessages: 0, cutChars: 0, lines: 6 });
  assert.ok(text.endsWith('\n') && !text.endsWith('\n\n'));
});

// Every tag the harness writes into a user message, each as Claude Code
// 2.1.286 writes it (the review of fix round 1), alone and appended after
// the person's words in the same string. The list is this test's own,
// never the module's: a tag the module stopped stripping fails here.
const HARNESS_SHAPES = [
  ['system-reminder', '<system-reminder>SECRET</system-reminder>'],
  ['system-reminder with an id', '<system-reminder id="0123456789abcdef0123456789abcdef">SECRET contents of ~/.ssh/config</system-reminder id="0123456789abcdef0123456789abcdef">'],
  ['task-notification', '<task-notification>\n<task-id>b1</task-id>\n<result>SECRET password=hunter2</result>\n</task-notification>'],
  ['command-message', '<command-message>SECRET</command-message>'],
  ['command-stdout', '<command-stdout>SECRET</command-stdout>'],
  ['command-stderr', '<command-stderr>SECRET</command-stderr>'],
  ['local-command-stdout', '<local-command-stdout>SECRET</local-command-stdout>'],
  ['local-command-stderr', '<local-command-stderr>SECRET</local-command-stderr>'],
  ['local-command-caveat', '<local-command-caveat>SECRET</local-command-caveat>'],
  ['bash-stdout', '<bash-stdout>SECRET</bash-stdout>'],
  ['bash-stderr', '<bash-stderr>SECRET</bash-stderr>'],
  ['bash-exit-code', '<bash-exit-code>SECRET</bash-exit-code>'],
  ['user-prompt-submit-hook', '<user-prompt-submit-hook>SECRET</user-prompt-submit-hook>'],
  ['agent-message', '<agent-message>SECRET</agent-message>'],
  ['fetched-web-content', '<fetched-web-content url="https://example.com">SECRET</fetched-web-content>'],
  ['coordinator-relay', '<coordinator-relay from="lead">SECRET</coordinator-relay>'],
  ['function_results', '<function_results>SECRET</function_results>'],
  ['fork-boilerplate', '<fork-boilerplate>SECRET</fork-boilerplate>'],
  ['teammate-message', '<teammate-message teammate_id="x">SECRET</teammate-message>'],
  ['cross-session-message', '<cross-session-message from="other">SECRET</cross-session-message>'],
  ['slack-tag-message', '<slack-tag-message channel="c">SECRET</slack-tag-message>'],
  ['forked-skill-launch', '<forked-skill-launch>SECRET</forked-skill-launch>'],
  ['message-files-missing', '<message-files-missing>SECRET</message-files-missing>'],
  ['ide_opened_file', '<ide_opened_file>The user opened the file /home/ana/SECRET in the IDE.</ide_opened_file>'],
  ['ide_selection', '<ide_selection>The user selected the lines 1 to 3 from /home/ana/secret.env:\nSECRET API_KEY=abc\n</ide_selection>'],
];

test('every block the harness writes into a user message is removed wherever it stands, with its attributes, and the person\'s own words around it stay', () => {
  const world = makeWorld();
  const lines = [];
  HARNESS_SHAPES.forEach(([, shape], i) => {
    lines.push(user(shape, MINUTE(2 * i)));
    lines.push(user(`Ana said ${i}\n\n${shape}`, MINUTE(2 * i + 1)));
  });
  const file = world.write(PROJECT, 'a.jsonl', lines);
  const plan = world.collect();
  const text = digestText(plan, file);
  for (const [name] of HARNESS_SHAPES) assert.doesNotMatch(text, /SECRET/, name);
  assert.deepEqual(bodyOf(plan, file).map((line) => line.replace(/^\[\d\d:\d\d user\] /, '')), HARNESS_SHAPES.map((_, i) => `Ana said ${i}`));
});

test('what the harness says on its own is dropped whole: a task notification behind its preamble, a Stop hook\'s feedback, a reminder behind a zero-width space; a reminder before the person\'s words keeps the words', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [
    user(`${PREAMBLE}<task-notification>\n<task-id>b1</task-id>\n<status>completed</status>\n<result>SECRET-SUBAGENT-REPORT</result>\n</task-notification>`, MINUTE(0)),
    user(`${PREAMBLE}SECRET-NOTIFICATION-TEXT with no block at all`, MINUTE(1)),
    user('Stop hook feedback:\n[node hooks/stop.mjs]: SECRET-STOP-HOOK', MINUTE(2)),
    user('\u200B<system-reminder>SECRET-ZWSP</system-reminder>', MINUTE(3)),
    user('<system-reminder>r</system-reminder>\nAna writes after the reminder', MINUTE(4)),
  ]);
  const plan = world.collect();
  assert.doesNotMatch(digestText(plan, file), /SECRET/);
  assert.deepEqual(bodyOf(plan, file), ['[01:04 user] Ana writes after the reminder']);
});

test('what the person typed inside the harness\'s tags stays as the person\'s words: a slash command with its arguments, a ! command', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [
    user('<command-message>brain-kit:capture</command-message>\n<command-name>/brain-kit:capture</command-name>\n<command-args>Ana decided to drop the vendor</command-args>', MINUTE(0)),
    user('<bash-input>git status</bash-input>', MINUTE(1)),
    user('<bash-input>ls</bash-input><bash-stdout>SECRET-LISTING</bash-stdout><bash-stderr></bash-stderr>', MINUTE(2)),
    user('<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>', MINUTE(3)),
  ]);
  const plan = world.collect();
  assert.deepEqual(bodyOf(plan, file), [
    '[01:00 user] /brain-kit:capture Ana decided to drop the vendor',
    '[01:01 user] git status',
    '[01:02 user] ls',
    '[01:03 user] /clear',
  ]);
});

test('a user line whose origin is not a person is dropped; one a person sent, or with no origin, stays (in doubt, include)', () => {
  const world = makeWorld();
  const lines = [];
  const notHuman = ['task-notification', 'peer', 'channel', 'plugin', 'auto-continuation', 'observer-activity', 'agent'];
  notHuman.forEach((kind, i) => lines.push(user(`SECRET-ORIGIN-${kind}`, MINUTE(i), { origin: { kind } })));
  lines.push({ ...user('SECRET-ORIGIN-ON-THE-MESSAGE', MINUTE(10)), message: { role: 'user', content: 'SECRET-ORIGIN-ON-THE-MESSAGE', origin: { kind: 'peer' } } });
  lines.push(user('typed here', MINUTE(20), { origin: { kind: 'human' } }));
  lines.push(user('typed from the phone', MINUTE(21), { origin: { kind: 'remote' } }));
  lines.push(user('a suggestion Ana sent', MINUTE(22), { origin: { kind: 'suggestion' } }));
  lines.push(user('no origin at all', MINUTE(23)));
  lines.push(user('an origin with no kind', MINUTE(24), { origin: {} }));
  const file = world.write(PROJECT, 'a.jsonl', lines);
  const plan = world.collect();
  assert.doesNotMatch(digestText(plan, file), /SECRET/);
  assert.deepEqual(bodyOf(plan, file).map((line) => line.slice(13)), ['typed here', 'typed from the phone', 'a suggestion Ana sent', 'no origin at all', 'an origin with no kind']);
});

test('a line the harness marks as its own is dropped on that mark alone: isMeta (a skill body), isCompactSummary, isVisibleInTranscriptOnly', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [
    meta('Base directory for this skill: /home/ana/.claude/skills/notes SECRET-SKILL-BODY', MINUTE(0)),
    { ...user('SECRET-COMPACT-FLAGGED', MINUTE(1)), isCompactSummary: true },
    { ...user('This session is being continued from a previous conversation. SECRET-TRANSCRIPT-ONLY', MINUTE(2)), isVisibleInTranscriptOnly: true },
    user('Ana stays', MINUTE(3)),
  ]);
  const plan = world.collect();
  assert.doesNotMatch(digestText(plan, file), /SECRET/);
  assert.deepEqual(bodyOf(plan, file), ['[01:03 user] Ana stays']);
});

test('a tag only quoted, a person\'s own "Caveat:", and the assistant\'s words are kept as written: in doubt, include', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [
    user('See <command-name> and Caveat: in the docs', MINUTE(0)),
    user('[Request interrupted by user]', MINUTE(1)),
    user('Caveat: Ana warns that the budget is a draft', MINUTE(2)),
    userBlocks([{ type: 'text', text: 'first block' }, { type: 'text', text: '<task-notification>x</task-notification>' }, { type: 'text', text: 'third block' }], MINUTE(3)),
    assistant('The tag <system-reminder>looks like this</system-reminder> in the docs', MINUTE(4)),
  ]);
  const plan = world.collect();
  assert.deepEqual(bodyOf(plan, file), [
    '[01:00 user] See <command-name> and Caveat: in the docs',
    '[01:01 user] [Request interrupted by user]',
    '[01:02 user] Caveat: Ana warns that the budget is a draft',
    '[01:03 user] first block third block',
    '[01:04 assistant] The tag <system-reminder>looks like this</system-reminder> in the docs',
  ]);
});

test('one huge message is cut at the message cap with a visible mark, never inside a character', () => {
  const world = makeWorld();
  const big = world.write(PROJECT, 'big.jsonl', [user('x'.repeat(5000), AT('10:00'))]);
  const astral = world.write(PROJECT, 'astral.jsonl', [user(`${'a'.repeat(DIGEST_LIMITS.messageChars - 1)}\u{1F600}tail`, AT('10:00'))]);
  const plan = world.collect();
  assert.deepEqual(bodyOf(plan, big), [`[07:00 user] ${'x'.repeat(DIGEST_LIMITS.messageChars)} ${DIGEST_CUT_MARK}`]);
  assert.deepEqual(bodyOf(plan, astral), [`[07:00 user] ${'a'.repeat(DIGEST_LIMITS.messageChars - 1)} ${DIGEST_CUT_MARK}`], 'the emoji is left out whole, not split in half');
  assert.equal(plan.files.find((f) => f.path === big).digest.cutMessages, 0, 'a message cut short is still kept: only its own mark says so');
});

// Sixty messages of a thousand characters on one day: more than one digest
// holds, so the day is cut from its start and its end is kept.
function longDay(world, name = 'long.jsonl', count = 60, size = 996) {
  const messages = [];
  for (let i = 0; i < count; i += 1) messages.push(user(`m${String(i).padStart(2, '0')} ${'w'.repeat(size)}`, MINUTE(i)));
  return world.write(PROJECT, name, messages);
}

for (const [lang, cut] of [
  ['en', (n, c) => `cut: the first ${n} messages and ${c} characters were left out`],
  ['pt-BR', (n, c) => `corte: as primeiras ${n} mensagens e ${c} caracteres ficaram de fora`],
]) {
  test(`${lang}: a lone day that holds more than a digest can carry keeps its END, and the header and the block both say what was cut`, () => {
    const world = makeWorld({ lang });
    const file = longDay(world);
    const plan = world.collect();
    const { digest } = plan.files[0];
    assert.ok(digest.kept > 10 && digest.kept < 60, JSON.stringify(digest));
    assert.equal(digest.held, 60);
    assert.equal(digest.cutMessages, 60 - digest.kept);
    assert.equal(digest.cutChars, digest.cutMessages * 1000);
    const lines = linesOf(digestText(plan, file));
    assert.ok(lines[0].endsWith(`${cut(digest.cutMessages, digest.cutChars)}.`), lines[0]);
    assert.ok(lines[1].includes(`] m${String(digest.cutMessages).padStart(2, '0')} `), 'the oldest kept is the first after the cut');
    assert.ok(lines.at(-1).includes('] m59 '), 'the newest is kept');
    const fileLine = plan.promptBlock.split('\n').find((l) => l.includes(digestOf(plan, file)));
    assert.ok(fileLine.endsWith(`; ${cut(digest.cutMessages, digest.cutChars)})`), fileLine);
    assert.deepEqual(plan.daysCovered, ['2026-09-23'], 'the one day still closes');
  });
}

// The smallest number of equal messages for which the digest leaves out
// exactly one.
function cutByOne(world) {
  for (let count = 2; count < 40; count += 1) {
    const file = longDay(world, `one-${count}.jsonl`, count, 1796);
    const plan = world.collect();
    const digest = plan.files.find((f) => f.path === file).digest;
    if (digest.cutMessages === 1) return { file, plan, digest };
    rmSync(file);
  }
  throw new Error('no count leaves out exactly one message');
}

test('a cut of exactly one message is said too, in the header and in the block', () => {
  const world = makeWorld();
  const { file, plan, digest } = cutByOne(world);
  assert.equal(digest.cutMessages, 1);
  assert.match(linesOf(digestText(plan, file))[0], /this digest keeps the last \d+; cut: the first 1 messages and 1800 characters were left out\.$/);
  const fileLine = plan.promptBlock.split('\n').find((l) => l.includes(digestOf(plan, file)));
  assert.match(fileLine, /; cut: the first 1 messages and 1800 characters were left out\)$/);
});

// The review's 3-day case (fix round 1, Important 3): one session with
// twelve messages of about 1 700 characters on each of 21, 22 and
// 23/09/2026. One day fits a digest whole, two do not: 21/09 is offered
// whole and 22 and 23/09 stay open, never cut away.
const THREE_DAYS = { from: new Date('2026-09-21T03:00:00.000Z'), to: new Date('2026-09-24T03:00:00.000Z'), timezone: TIMEZONE, days: ['2026-09-21', '2026-09-22', '2026-09-23'] };

function threeDays(world, name = 'dddddddd-1111-4222-8333-444444444444.jsonl', perDay = 12) {
  const lines = [];
  for (const [day, tag] of [['2026-09-21', 'DAY21'], ['2026-09-22', 'DAY22'], ['2026-09-23', 'DAY23']]) {
    for (let i = 0; i < perDay; i += 1) {
      const at = new Date(Date.parse(`${day}T12:00:00.000Z`) + i * 60_000).toISOString();
      lines.push(i % 2 ? assistant(`${tag} reply ${i} ${'x'.repeat(1700)}`, at) : user(`${tag} Ana said ${i} ${'y'.repeat(1700)}`, at));
    }
  }
  return world.write(PROJECT, name, lines);
}

for (const [lang, note, block] of [
  ['en', 'The days 22/09/2026, 23/09/2026 stay open for a later round: this round\'s digests could not hold them whole after the days before them.', /^The days 22\/09\/2026, 23\/09\/2026 wait for a later round: the digest of session dddddddd could not hold them whole after the days before them, and a digest must stay readable whole \(under 24000 bytes as Read prints it\)\. Only whole days are offered; 1 transcripts with messages only on those days wait with them\.$/],
  ['pt-BR', 'Os dias 22/09/2026, 23/09/2026 ficam abertos para uma próxima rodada: os extratos desta rodada não conseguiram guardá-los inteiros depois dos dias anteriores.', /^Os dias 22\/09\/2026, 23\/09\/2026 ficam para uma próxima rodada: o extrato da sessão dddddddd não conseguiu guardá-los inteiros/],
]) {
  test(`${lang}: a digest that cannot hold every day of the window offers whole days, oldest first, and leaves the others open, said in the header and the block`, () => {
    const world = makeWorld({ lang });
    const file = threeDays(world);
    world.write(PROJECT, 'eeeeeeee-1111-4222-8333-444444444444.jsonl', [user('only on the last day', '2026-09-23T15:00:00.000Z')]);
    const plan = transcriptsSource.collect({ window: THREE_DAYS, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
    assert.deepEqual(plan.daysCovered, ['2026-09-21']);
    assert.deepEqual(plan.daysDeferred, ['2026-09-22', '2026-09-23']);
    assert.deepEqual(plan.digestDeferred, ['2026-09-22', '2026-09-23']);
    assert.deepEqual(plan.digestLimitedBy, ['dddddddd']);
    assert.equal(plan.window.to, '2026-09-22T03:00:00.000Z', 'the window, and so the mark, end at the last day offered whole');
    assert.deepEqual(plan.files.map((f) => f.path), [file], 'a session with nothing on the covered day waits');
    assert.equal(plan.dropped.byDigest, 1);
    assert.equal(plan.files[0].lastAt.slice(0, 10), '2026-09-21');
    const text = digestText(plan, file);
    assert.equal((text.match(/\] DAY21 /g) ?? []).length, 12, 'the day offered is offered whole');
    assert.doesNotMatch(text, /DAY22|DAY23/, 'the days left are not in it, not even in part');
    assert.equal(plan.files[0].digest.cutMessages, 0);
    assert.ok(linesOf(text)[0].endsWith(note), linesOf(text)[0]);
    assert.ok(plan.promptBlock.split('\n').some((line) => block.test(line)), plan.promptBlock);
    assert.ok(printedBytes(text) < DIGEST_LIMITS.readBytes);
  });
}

test('a first day that alone does not fit is the one cut, from its end, and the later days stay open whole', () => {
  const world = makeWorld();
  const file = threeDays(world, 'dddddddd-1111-4222-8333-444444444444.jsonl', 16);
  const plan = transcriptsSource.collect({ window: THREE_DAYS, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  assert.deepEqual(plan.daysCovered, ['2026-09-21']);
  assert.deepEqual(plan.digestDeferred, ['2026-09-22', '2026-09-23']);
  const { digest } = plan.files[0];
  assert.ok(digest.cutMessages > 0 && digest.kept > 0, JSON.stringify(digest));
  const text = digestText(plan, file);
  assert.ok(text.includes('] DAY21 reply 15 '), 'the end of the first day is kept');
  assert.doesNotMatch(text, /DAY22|DAY23/);
  assert.match(linesOf(text)[0], /cut: the first \d+ messages and \d+ characters were left out\. The days 22\/09\/2026, 23\/09\/2026 stay open/);
});

test('days that all fit are all offered, and no day is left', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [user('first day', '2026-09-21T13:00:00.000Z'), user('second day', '2026-09-22T13:00:00.000Z'), user('third day', '2026-09-23T13:00:00.000Z')]);
  const plan = transcriptsSource.collect({ window: THREE_DAYS, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  assert.deepEqual(plan.daysCovered, THREE_DAYS.days);
  assert.deepEqual(plan.digestDeferred, []);
  assert.deepEqual(bodyOf(plan, file), ['[21/09 10:00 user] first day', '[22/09 10:00 user] second day', '[23/09 10:00 user] third day']);
});

// The bound (ruling R-D1 of fix round 1): what Read prints for a digest,
// its numbers included, stays under DIGEST_LIMITS.readBytes UTF-8 bytes,
// and every token covers at least one byte, so it is under Read's 25 000
// tokens whatever the script. Each case fills one day with far more than a
// digest holds, of the script that costs the most bytes per character, or
// the most lines: the digest is cut, and what Read prints is still under
// the bound, and accepted whole.
const LONG_PROJECT = `-home-ana-${'p'.repeat(245)}`;
const SCRIPTS = [
  ['Chinese', () => '漢'.repeat(DIGEST_LIMITS.messageChars)],
  ['emoji', () => '\u{1F600}'.repeat(DIGEST_LIMITS.messageChars / 2)],
  ['base64', (i) => Buffer.from(Array.from({ length: 1350 }, (_, k) => (i * 31 + k * 7) % 256)).toString('base64')],
  ['Portuguese', () => 'ação de revisão com acentuação '.repeat(58)],
  ['many short lines', () => 'ok'],
];

for (const lang of ['en', 'pt-BR']) {
  test(`${lang}: whatever the script, what Read prints for a digest stays under 24 000 bytes, so under 25 000 tokens, and is read whole`, () => {
    const world = makeWorld({ lang, include: [LONG_PROJECT] });
    const files = SCRIPTS.map(([name, text]) => {
      const count = name === 'many short lines' ? 3000 : 200;
      const lines = [];
      for (let i = 0; i < count; i += 1) lines.push(assistant(text(i), new Date(FROM.getTime() + i * 20_000).toISOString()));
      return [name, world.write(LONG_PROJECT, `${name.replace(/ /g, '-')}.jsonl`, lines)];
    });
    const plan = world.collect();
    writeDigests(plan);
    for (const [name, file] of files) {
      const path = digestOf(plan, file);
      const text = readFileSync(path, 'utf8');
      const lines = linesOf(text);
      const printed = printedBytes(text);
      assert.ok(printed < DIGEST_LIMITS.readBytes, `${name}: Read prints ${printed} bytes`);
      assert.ok(printed > 20_000, `${name}: the budget is used (${printed} bytes)`);
      assert.ok(printed <= READ_MAX_TOKENS, `${name}: at most ${READ_MAX_TOKENS} tokens`);
      assert.ok(statSync(path).size < READ_MAX_BYTES);
      assert.ok(lines.length < READ_DEFAULT_LINES, `${name}: ${lines.length} lines`);
      assert.ok(lines.every((line) => line.length < 2000), `${name}: no line Read would cut`);
      // The kit's own reckoning of a line (its bytes, its newline, 12 for
      // Read's number) never counts less than what Read prints.
      const reckoned = lines.reduce((sum, line) => sum + Buffer.byteLength(line) + 1 + DIGEST_LIMITS.lineBytes, 0);
      assert.ok(reckoned >= Buffer.byteLength(numbered(lines)), name);
      assert.ok(reckoned < DIGEST_LIMITS.readBytes, `${name}: reckoned ${reckoned}`);
      const read = emulateRead({ file_path: path });
      assert.equal(read.isError, false, `${name}: ${read.content.slice(0, 200)}`);
      assert.ok(plan.files.find((f) => f.path === file).digest.cutMessages > 0, `${name}: cut, and said`);
    }
    const header = linesOf(readFileSync(digestOf(plan, files[0][1]), 'utf8'))[0];
    assert.ok(header.length < 1000, `the longest header (${header.length} characters, a 255-character project)`);
  });
}

test('a window of more than one day puts the date in front of each time, on the vault\'s wall clock', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [user('first day', AT('10:00')), user('second day', '2026-09-24T10:00:00.000Z')]);
  const window = { from: FROM, to: new Date(TO.getTime() + 24 * 3600 * 1000), timezone: TIMEZONE };
  const plan = transcriptsSource.collect({ window, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  assert.deepEqual(bodyOf(plan, file), ['[23/09 07:00 user] first day', '[24/09 07:00 user] second day']);
});

test('a time zone the platform does not know stamps the digest in UTC, and its header says so', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [user('Ana asks', AT('10:00'))]);
  const plan = transcriptsSource.collect({ window: { from: FROM, to: TO, timezone: 'Not/A_Zone' }, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  const lines = linesOf(digestText(plan, file));
  assert.match(lines[0], /each with its time in UTC\./);
  assert.equal(lines[1], '[10:00 user] Ana asks');
});

test('a digest covers only the days the plan covers: a message on a day the cap defers belongs to a later round', () => {
  const world = makeWorld({ cap: 1 });
  const both = world.write(PROJECT, 'both.jsonl', [user('on the first day', AT('10:00')), user('on the deferred day', '2026-09-24T10:00:00.000Z')]);
  world.write(PROJECT, 'later.jsonl', [user('only on the deferred day', '2026-09-24T11:00:00.000Z')]);
  const window = { from: FROM, to: new Date(TO.getTime() + 24 * 3600 * 1000), timezone: TIMEZONE };
  const plan = transcriptsSource.collect({ window, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  assert.deepEqual(plan.daysCovered, ['2026-09-23']);
  assert.deepEqual(plan.digestDeferred, [], 'the cap deferred it, not a digest');
  assert.deepEqual(plan.files.map((f) => f.path), [both]);
  assert.deepEqual(bodyOf(plan, both), ['[07:00 user] on the first day'], 'one day covered: no date in front, and nothing of the deferred day');
  assert.match(plan.promptBlock, /1 transcripts wait for a later round: every message they have in the window falls on 24\/09\/2026, days the cap of 1/);
});

test('a kept transcript whose window holds no text of anyone still gets a digest, which says it held nothing', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'tools.jsonl', [
    user('the question was yesterday', '2026-09-22T20:00:00.000Z'),
    userBlocks([{ type: 'tool_result', tool_use_id: 'toolu_9', content: 'SECRET-LATE-RESULT' }], AT('03:30')),
  ]);
  const plan = world.collect();
  const text = digestText(plan, file);
  assert.match(linesOf(text)[0], /The window held 0 messages; this digest keeps 0\.$/);
  assert.equal(linesOf(text).length, 1);
  assert.doesNotMatch(text, /SECRET/);
});

test('writeDigests writes each digest owner-only (0600) in a folder of its own (0700), never over a file already there, and nothing for a plan with none', () => {
  const world = makeWorld();
  world.write(PROJECT, 'a.jsonl', [user('Ana asks', AT('10:00'))]);
  world.write(PROJECT, 'b.jsonl', [user('Ana asks again', AT('11:00'))]);
  const plan = world.collect();
  const old = process.umask(0o000);
  try {
    assert.equal(writeDigests(plan), 2);
  } finally {
    process.umask(old);
  }
  assert.equal(statSync(world.digestDir).mode & 0o777, 0o700);
  assert.equal(statSync(dirname(world.digestDir)).mode & 0o777, 0o700);
  for (const file of plan.files) {
    assert.equal(statSync(file.digest.path).mode & 0o777, 0o600);
    assert.equal(readFileSync(file.digest.path, 'utf8'), plan.digestTexts.find((d) => d.path === file.digest.path).text);
  }
  assert.throws(() => writeDigests(plan), /EEXIST/, 'a second write never replaces a digest');
  assert.equal(JSON.stringify(plan).includes('Ana asks'), false, 'no JSON copy of the plan carries a digest\'s text');
  assert.equal(writeDigests({ files: [] }), 0);
  const bare = transcriptsSource.collect({ window: { from: FROM, to: TO }, config: world.config, machine: world.machine, now: NOW });
  assert.equal(writeDigests(bare), 0);
  rmSync(world.digestDir, { recursive: true });
});

test('a transcript that cannot be read again for its digest leaves the offer for the unreadable list: its day stays open', () => {
  const world = makeWorld();
  const fine = world.write(PROJECT, 'fine.jsonl', [user('Ana asks', AT('10:00'))]);
  const flaky = world.write(PROJECT, 'flaky.jsonl', [user('Ana asks again', AT('11:00'))]);
  let opens = 0;
  const io = {
    openSync: (path, flags) => {
      if (path === flaky && (opens += 1) > 1) throw Object.assign(new Error('EIO: i/o error'), { code: 'EIO' });
      return openSync(path, flags);
    },
    readSync,
    closeSync,
  };
  const plan = transcriptsSource.collect({ window: { from: FROM, to: TO }, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir, io });
  assert.deepEqual(plan.files.map((f) => f.path), [fine]);
  assert.deepEqual(plan.unreadable, [{ path: flaky, project: PROJECT, bytes: statSync(flaky).size }]);
  assert.equal(plan.dropped.unreadable, 1);
  assert.deepEqual(plan.digestTexts.map((d) => d.path), [digestOf(plan, fine)]);
  assert.deepEqual(transcriptsSource.readEvidence({ toolUses: [{ id: 'u', name: 'Read', input: { file_path: digestOf(plan, fine) } }], toolResults: [{ toolUseId: 'u', isError: false }] }, plan), { read: 1, expected: 2, ok: false });
});

test('every message key of the digest renders in both packs with nothing left over', () => {
  for (const lang of ['en', 'pt-BR']) {
    const t = createTranslator(lang);
    const cut = t('sources.transcripts.digest_cut', { messages: 3, chars: 120 });
    const header = t('sources.transcripts.digest_header_cut', { session: 's', project: 'p', from: 'a', to: 'b', timezone: 'UTC', held: 9, kept: 6, cut });
    assert.doesNotMatch(header, /\{[a-z]+\}/, lang);
    assert.ok(header.includes(cut), lang);
    assert.doesNotMatch(t('sources.transcripts.digest_days_left', { days: '22/09/2026' }), /\{[a-z]+\}/, lang);
  }
});
