// The digest of a transcript (src/sources/transcripts-claude-code.mjs):
// what the model reads in place of each kept transcript since 01/10/2026,
// when the first real round on a real vault found transcripts the Read
// tool refuses (docs/incidents.md). What it holds (only the person's and
// the assistant's own text inside the window, in order of time), what it
// never holds (tool calls, tool results, thinking, the harness's wrappers),
// how it is cut (each message, and the whole, keeping the end, every cut
// said in the vault's language), and the proof that the largest digest the
// limits allow is still one Read whole. Every transcript here is built by
// hand (test/helpers/transcripts-world.mjs); no test reads a real one.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { closeSync, openSync, readFileSync, readSync, rmSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createTranslator } from '../src/lang.mjs';
import { DIGEST_CUT_MARK, DIGEST_LIMITS, HARNESS_PREFIXES, transcriptsSource, writeDigests } from '../src/sources/transcripts-claude-code.mjs';
import {
  FROM, TO, NOW, PROJECT, TIMEZONE, assistant, digestOf, digestText, makeWorld, meta, system, user, userBlocks,
} from './helpers/transcripts-world.mjs';
import { CHARS_PER_TOKEN, emulateRead, estimateTokens, LINE_PREFIX_CHARS, linesOf, READ_DEFAULT_LINES, READ_MAX_BYTES, READ_MAX_TOKENS } from './helpers/read-tool.mjs';

function assistantBlocks(blocks, timestamp) {
  return { ...assistant('', timestamp), message: { role: 'assistant', content: blocks } };
}

// The window of the world is 23/09/2026 in UTC-3: [03:00Z, next day 03:00Z).
const AT = (hhmm) => `2026-09-23T${hhmm}:00.000Z`;

test('a digest holds exactly the in-window text of the person and the assistant, in order of time, under its header, and nothing of a tool, a thought or the harness', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'aaaaaaaa-1111-4222-8333-444444444444.jsonl', [
    user('Before the window', '2026-09-23T02:59:59.999Z'),
    user('Ana opens the day', '2026-09-23T03:00:00.000Z'),
    assistantBlocks([
      { type: 'thinking', thinking: 'SECRET-THINKING', signature: 'c2ln' },
      { type: 'text', text: 'Here is the plan' },
      { type: 'tool_use', id: 'toolu_1', name: 'Bash', input: { command: 'SECRET-COMMAND' } },
    ], AT('13:00')),
    userBlocks([{ type: 'tool_result', tool_use_id: 'toolu_1', content: [{ type: 'text', text: 'SECRET-TOOL-RESULT' }] }], AT('13:01')),
    userBlocks([{ type: 'tool_result', tool_use_id: 'toolu_2', content: 'SECRET-TOOL-STRING' }], AT('13:02')),
    userBlocks([{ type: 'text', text: '<system-reminder>SECRET-REMINDER</system-reminder>' }, { type: 'text', text: 'Ana asks  about\n\nthe \t budget' }], AT('14:00')),
    meta('Caveat: SECRET-CAVEAT. The messages below were generated by the user while running local commands.', AT('14:01')),
    user('<command-message>clear</command-message>\n<command-name>/clear</command-name>\n<command-args>SECRET-ARGS</command-args>', AT('14:02')),
    user('<command-name>/compact</command-name>', AT('14:03')),
    user('<local-command-stdout>SECRET-STDOUT</local-command-stdout>', AT('14:04')),
    user('<local-command-caveat>SECRET-LOCAL-CAVEAT</local-command-caveat>', AT('14:05')),
    user('<task-notification>SECRET-TASK</task-notification>', AT('14:06')),
    user('<bash-stdout>SECRET-BASH-OUT</bash-stdout>', AT('14:07')),
    user('<user-prompt-submit-hook>SECRET-HOOK</user-prompt-submit-hook>', AT('14:08')),
    user(' \n <system-reminder>SECRET-INDENTED</system-reminder>', AT('14:09')),
    user('Caveat: SECRET-CAVEAT-NOT-META', AT('14:10')),
    assistantBlocks([{ type: 'thinking', thinking: 'SECRET-THINKING-ONLY', signature: 'c2ln' }], AT('14:11')),
    user('Ana quotes the tag <system-reminder> in a sentence about the logs', AT('15:00')),
    { ...user('SECRET-COMPACT-SUMMARY of an earlier conversation', AT('15:01')), isCompactSummary: true },
    system(AT('15:02')),
    user('At the end of the window', '2026-09-24T03:00:00.000Z'),
    // Written later in the file, said earlier: the digest goes by time.
    assistant('An earlier answer, written later in the file', AT('12:30')),
  ]);
  const plan = world.collect();
  const text = digestText(plan, file);
  const lines = linesOf(text);
  assert.equal(lines[0], `Digest of session aaaaaaaa (project ${PROJECT}), made by the kit from its transcript: the messages written between ${FROM.toISOString()} and ${TO.toISOString()} (UTC), one per line, each with its time in ${TIMEZONE}. The window held 5 messages; this digest keeps 5.`);
  assert.deepEqual(lines.slice(1), [
    '[00:00 user] Ana opens the day',
    '[09:30 assistant] An earlier answer, written later in the file',
    '[10:00 assistant] Here is the plan',
    '[11:00 user] Ana asks about the budget',
    '[12:00 user] Ana quotes the tag <system-reminder> in a sentence about the logs',
  ]);
  assert.doesNotMatch(text, /SECRET/, 'no tool use, tool result, thought, wrapper or compact summary');
  assert.doesNotMatch(text, /Before the window|At the end of the window/, 'the window is [from, to): its end is out');
  assert.deepEqual(plan.files[0].digest, { path: join(world.digestDir, '01-aaaaaaaa.txt'), held: 5, kept: 5, cutMessages: 0, cutChars: 0, lines: 6 });
  assert.ok(text.endsWith('\n') && !text.endsWith('\n\n'));
});

test('a wrapper only counts at the start of a block: in doubt, the text is kept', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [
    user('See <command-name> and Caveat: in the docs', AT('10:00')),
    user('[Request interrupted by user]', AT('10:01')),
    userBlocks([{ type: 'text', text: 'first block' }, { type: 'text', text: '<task-notification>x</task-notification>' }, { type: 'text', text: 'third block' }], AT('10:02')),
  ]);
  const lines = linesOf(digestText(world.collect(), file)).slice(1);
  assert.deepEqual(lines, [
    '[07:00 user] See <command-name> and Caveat: in the docs',
    '[07:01 user] [Request interrupted by user]',
    '[07:02 user] first block third block',
  ]);
  assert.ok(HARNESS_PREFIXES.includes('<system-reminder>') && HARNESS_PREFIXES.includes('Caveat:'));
});

test('one huge message is cut at the message cap with a visible mark, never inside a character', () => {
  const world = makeWorld();
  const big = world.write(PROJECT, 'big.jsonl', [user('x'.repeat(5000), AT('10:00'))]);
  const astral = world.write(PROJECT, 'astral.jsonl', [user(`${'a'.repeat(DIGEST_LIMITS.messageChars - 1)}\u{1F600}tail`, AT('10:00'))]);
  const plan = world.collect();
  const [line] = linesOf(digestText(plan, big)).slice(1);
  assert.equal(line, `[07:00 user] ${'x'.repeat(DIGEST_LIMITS.messageChars)} ${DIGEST_CUT_MARK}`);
  const [cut] = linesOf(digestText(plan, astral)).slice(1);
  assert.equal(cut, `[07:00 user] ${'a'.repeat(DIGEST_LIMITS.messageChars - 1)} ${DIGEST_CUT_MARK}`, 'the emoji is left out whole, not split in half');
  assert.equal(plan.files.find((f) => f.path === big).digest.cutMessages, 0, 'a message cut short is still kept: only its own mark says so');
});

for (const [lang, header, block] of [
  ['en', /The window held 60 messages; this digest keeps the last 39; cut: the first 21 messages and 21000 characters were left out\.$/, /the digest keeps the last 39 of 60 messages; cut: the first 21 messages and 21000 characters were left out\)$/],
  ['pt-BR', /A janela teve 60 mensagens; este extrato guarda as últimas 39; corte: as primeiras 21 mensagens e 21000 caracteres ficaram de fora\.$/, /o extrato guarda as últimas 39 de 60 mensagens; corte: as primeiras 21 mensagens e 21000 caracteres ficaram de fora\)$/],
]) {
  test(`${lang}: a window that holds more than a digest can carry keeps the END, and the header and the block both say what was cut`, () => {
    const world = makeWorld({ lang });
    const messages = [];
    for (let i = 0; i < 60; i += 1) messages.push(user(`m${String(i).padStart(2, '0')} ${'w'.repeat(996)}`, new Date(Date.parse(AT('04:00')) + i * 60_000).toISOString()));
    const file = world.write(PROJECT, 'long.jsonl', messages);
    const plan = world.collect();
    const lines = linesOf(digestText(plan, file));
    assert.match(lines[0], header);
    assert.equal(lines.length, 40);
    assert.ok(lines[1].includes('] m21 '), 'the oldest kept is the 22nd message');
    assert.ok(lines.at(-1).includes('] m59 '), 'the newest is kept');
    assert.equal(lines.some((line) => line.includes('] m20 ')), false);
    assert.deepEqual(plan.files[0].digest, { path: digestOf(plan, file), held: 60, kept: 39, cutMessages: 21, cutChars: 21000, lines: 40 });
    const fileLine = plan.promptBlock.split('\n').find((l) => l.includes(digestOf(plan, file)));
    assert.match(fileLine, block);
  });
}

test('a window of many short messages keeps the last ones the line cap allows, and says how many it left out', () => {
  const world = makeWorld();
  const messages = [];
  for (let i = 0; i < DIGEST_LIMITS.messages + 200; i += 1) messages.push(user(`ok ${i}`, new Date(Date.parse(AT('04:00')) + i * 1000).toISOString()));
  const file = world.write(PROJECT, 'chatty.jsonl', messages);
  const plan = world.collect();
  const digest = plan.files[0].digest;
  assert.equal(digest.kept, DIGEST_LIMITS.messages);
  assert.equal(digest.cutMessages, 200);
  assert.equal(digest.cutChars, Array.from({ length: 200 }, (_, i) => `ok ${i}`.length).reduce((a, b) => a + b, 0));
  const lines = linesOf(digestText(plan, file));
  assert.equal(lines.length, DIGEST_LIMITS.messages + 1);
  assert.ok(lines[1].endsWith('] ok 200'));
  assert.match(lines[0], /cut: the first 200 messages and \d+ characters were left out/);
});

// The proof the brief asks for. Read refuses a whole file over 256 KB and
// anything over 25 000 tokens, reads 2 000 lines without a limit, and
// numbers every line it returns. A digest at its largest is the header (at
// most HEADER_MAX characters: the longest pack's sentence with a project
// name of 255 characters, the longest a file system allows) plus
// DIGEST_LIMITS.totalChars characters of message lines on at most
// DIGEST_LIMITS.messages lines. Bytes: UTF-8 spends at most 3 bytes per
// UTF-16 unit (a character outside the BMP is 4 bytes for 2 units), so at
// most 3 bytes per character. Tokens: CHARS_PER_TOKEN, 2 characters per
// token over what Read returns, line numbers included, is a deliberately
// pessimistic ratio (test/helpers/read-tool.mjs): Claude's tokenizer runs
// near 4 characters per token on English and about 3 on Portuguese.
const HEADER_MAX = 1000;
const LONG_PROJECT = `-home-ana-${'p'.repeat(245)}`;

test('the bound itself: the largest digest the limits allow is under every limit of the Read tool', () => {
  const chars = HEADER_MAX + 1 + DIGEST_LIMITS.totalChars;
  const lines = DIGEST_LIMITS.messages + 1;
  assert.ok(3 * chars < READ_MAX_BYTES, `${3 * chars} bytes at most`);
  assert.ok(lines <= READ_DEFAULT_LINES, 'read whole without a limit');
  // Read's numbering, given 8 columns to be safe (cat -n uses 7 below a
  // million lines).
  const tokens = Math.ceil((chars + lines * (LINE_PREFIX_CHARS + 1)) / CHARS_PER_TOKEN);
  assert.ok(tokens < READ_MAX_TOKENS, `${tokens} tokens at most`);
  assert.ok(24 + DIGEST_LIMITS.messageChars + 1 + DIGEST_CUT_MARK.length < 2000, 'no message line long enough for Read to cut');
});

for (const lang of ['en', 'pt-BR']) {
  test(`${lang}: the worst digests, built for real, are read whole under 256 KB and 25 000 tokens`, () => {
    const world = makeWorld({ lang, include: [LONG_PROJECT] });
    // Two days, so every line carries its date: the widest prefix.
    const window = { from: FROM, to: new Date(TO.getTime() + 24 * 3600 * 1000), timezone: TIMEZONE };
    // Most bytes: every message a 3-byte character, cut at the cap.
    const heavy = [];
    for (let i = 0; i < 200; i += 1) heavy.push(assistant('€'.repeat(5000), new Date(FROM.getTime() + i * 60_000).toISOString()));
    const bytesFile = world.write(LONG_PROJECT, 'bytes.jsonl', heavy);
    // Most lines and most characters at once: 25 characters of text after
    // the 24-character prefix fill both caps exactly.
    const dense = [];
    for (let i = 0; i < 3 * DIGEST_LIMITS.messages; i += 1) dense.push(assistant(`ação ${String(i).padStart(20, '0')}`, new Date(FROM.getTime() + i * 1000).toISOString()));
    const linesFile = world.write(LONG_PROJECT, 'lines.jsonl', dense);
    const plan = transcriptsSource.collect({ window, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
    writeDigests(plan);
    for (const [file, what] of [[bytesFile, 'bytes'], [linesFile, 'lines']]) {
      const path = digestOf(plan, file);
      const text = readFileSync(path, 'utf8');
      const lines = linesOf(text);
      assert.ok(lines[0].length < HEADER_MAX, `${what}: header of ${lines[0].length} characters`);
      assert.ok(lines.every((line) => line.length < 2000), `${what}: no line Read would cut`);
      assert.ok(text.length <= HEADER_MAX + 1 + DIGEST_LIMITS.totalChars, `${what}: ${text.length} characters`);
      const bytes = statSync(path).size;
      assert.ok(bytes < READ_MAX_BYTES, `${what}: ${bytes} bytes`);
      const read = emulateRead({ file_path: path });
      assert.equal(read.isError, false, `${what}: ${read.content.slice(0, 200)}`);
      assert.ok(estimateTokens(read.content) < READ_MAX_TOKENS, `${what}: ${estimateTokens(read.content)} tokens`);
      assert.match(lines[1], /^\[\d\d\/\d\d \d\d:\d\d assistant\] /);
    }
    const dense0 = plan.files.find((f) => f.path === linesFile).digest;
    assert.equal(dense0.kept, DIGEST_LIMITS.messages, 'the line cap and the character cap both reached');
    // Each message line costs its length and its newline: 800 lines of 50.
    assert.equal(linesOf(readFileSync(digestOf(plan, linesFile), 'utf8')).slice(1).join('\n').length + 1, DIGEST_LIMITS.totalChars);
    assert.ok(statSync(digestOf(plan, bytesFile)).size > 100_000, 'the byte case really is heavy');
  });
}

test('a window of more than one day puts the date in front of each time, on the vault\'s wall clock', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [user('first day', AT('10:00')), user('second day', '2026-09-24T10:00:00.000Z')]);
  const window = { from: FROM, to: new Date(TO.getTime() + 24 * 3600 * 1000), timezone: TIMEZONE };
  const plan = transcriptsSource.collect({ window, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  assert.deepEqual(linesOf(digestText(plan, file)).slice(1), ['[23/09 07:00 user] first day', '[24/09 07:00 user] second day']);
});

test('a time zone the platform does not know stamps the digest in UTC, and its header says so', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'a.jsonl', [user('Ana asks', AT('10:00'))]);
  const plan = transcriptsSource.collect({ window: { from: FROM, to: TO, timezone: 'Not/A_Zone' }, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  const lines = linesOf(digestText(plan, file));
  assert.match(lines[0], /each with its time in UTC\./);
  assert.equal(lines[1], '[10:00 user] Ana asks');
});

test('a digest covers only the days the plan covers: a message on a day the cap defers belongs to a later round', () => {
  const world = makeWorld({ cap: 1 });
  const both = world.write(PROJECT, 'both.jsonl', [user('on the first day', AT('10:00')), user('on the deferred day', '2026-09-24T10:00:00.000Z')]);
  world.write(PROJECT, 'later.jsonl', [user('only on the deferred day', '2026-09-24T11:00:00.000Z')]);
  const window = { from: FROM, to: new Date(TO.getTime() + 24 * 3600 * 1000), timezone: TIMEZONE };
  const plan = transcriptsSource.collect({ window, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir });
  assert.deepEqual(plan.daysCovered, ['2026-09-23']);
  assert.deepEqual(plan.files.map((f) => f.path), [both]);
  assert.deepEqual(linesOf(digestText(plan, both)).slice(1), ['[07:00 user] on the first day'], 'one day covered: no date in front, and nothing of the deferred day');
});

test('a kept transcript whose window holds no text of anyone still gets a digest, which says it held nothing', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'tools.jsonl', [
    user('the question was yesterday', '2026-09-22T20:00:00.000Z'),
    userBlocks([{ type: 'tool_result', tool_use_id: 'toolu_9', content: 'SECRET-LATE-RESULT' }], AT('03:30')),
  ]);
  const plan = world.collect();
  const text = digestText(plan, file);
  assert.match(linesOf(text)[0], /The window held 0 messages; this digest keeps 0\.$/);
  assert.equal(linesOf(text).length, 1);
  assert.doesNotMatch(text, /SECRET/);
});

test('writeDigests writes each digest owner-only (0600) in a folder of its own (0700), never over a file already there, and nothing for a plan with none', () => {
  const world = makeWorld();
  world.write(PROJECT, 'a.jsonl', [user('Ana asks', AT('10:00'))]);
  world.write(PROJECT, 'b.jsonl', [user('Ana asks again', AT('11:00'))]);
  const plan = world.collect();
  const old = process.umask(0o000);
  try {
    assert.equal(writeDigests(plan), 2);
  } finally {
    process.umask(old);
  }
  assert.equal(statSync(world.digestDir).mode & 0o777, 0o700);
  assert.equal(statSync(dirname(world.digestDir)).mode & 0o777, 0o700);
  for (const file of plan.files) {
    assert.equal(statSync(file.digest.path).mode & 0o777, 0o600);
    assert.equal(readFileSync(file.digest.path, 'utf8'), plan.digestTexts.find((d) => d.path === file.digest.path).text);
  }
  assert.throws(() => writeDigests(plan), /EEXIST/, 'a second write never replaces a digest');
  assert.equal(JSON.stringify(plan).includes('Ana asks'), false, 'no JSON copy of the plan carries a digest\'s text');
  assert.equal(writeDigests({ files: [] }), 0);
  const bare = transcriptsSource.collect({ window: { from: FROM, to: TO }, config: world.config, machine: world.machine, now: NOW });
  assert.equal(writeDigests(bare), 0);
  rmSync(world.digestDir, { recursive: true });
});

test('a transcript that cannot be read again for its digest leaves the offer for the unreadable list: its day stays open', () => {
  const world = makeWorld();
  const fine = world.write(PROJECT, 'fine.jsonl', [user('Ana asks', AT('10:00'))]);
  const flaky = world.write(PROJECT, 'flaky.jsonl', [user('Ana asks again', AT('11:00'))]);
  let opens = 0;
  const io = {
    openSync: (path, flags) => {
      if (path === flaky && (opens += 1) > 1) throw Object.assign(new Error('EIO: i/o error'), { code: 'EIO' });
      return openSync(path, flags);
    },
    readSync,
    closeSync,
  };
  const plan = transcriptsSource.collect({ window: { from: FROM, to: TO }, config: world.config, machine: world.machine, now: NOW, digestDir: world.digestDir, io });
  assert.deepEqual(plan.files.map((f) => f.path), [fine]);
  assert.deepEqual(plan.unreadable, [{ path: flaky, project: PROJECT, bytes: statSync(flaky).size }]);
  assert.equal(plan.dropped.unreadable, 1);
  assert.deepEqual(plan.digestTexts.map((d) => d.path), [digestOf(plan, fine)]);
  assert.deepEqual(transcriptsSource.readEvidence({ toolUses: [{ id: 'u', name: 'Read', input: { file_path: digestOf(plan, fine) } }], toolResults: [{ toolUseId: 'u', isError: false }] }, plan), { read: 1, expected: 2, ok: false });
});

test('every message key of the digest renders in both packs with nothing left over', () => {
  for (const lang of ['en', 'pt-BR']) {
    const t = createTranslator(lang);
    const cut = t('sources.transcripts.digest_cut', { messages: 3, chars: 120 });
    const header = t('sources.transcripts.digest_header_cut', { session: 's', project: 'p', from: 'a', to: 'b', timezone: 'UTC', held: 9, kept: 6, cut });
    assert.doesNotMatch(header, /\{[a-z]+\}/, lang);
    assert.ok(header.includes(cut), lang);
  }
});
