// docs/incidents.md, 11/08/2026: the self-trace filter ate the day's work.
// The scheduled curator discarded every transcript that held its prompt
// signature anywhere in the file, so a human session that had merely
// opened the prompt file was discarded as if it were the curator, and the
// day's working sessions vanished. The rule: recognize the curator's own
// runs only by the first user message, parsed as JSON; in doubt the
// transcript stays in.
//
// Phase 2 (this file): src/sources/transcripts-claude-code.mjs drops a
// file as `selfTrace` only when its FIRST user line that is not `isMeta`
// and carries text (a string, or text blocks; a line holding only
// tool_result blocks is passed over) starts, trimmed, with
// `curate.signature` or one of `curate.extra_signatures`.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  INSIDE, PROJECT, SIGNATURE, assistant, customTitle, makeWorld, meta, paths, toolResult, user, userBlocks,
} from '../helpers/transcripts-world.mjs';

const LATER = '2026-09-23T15:00:00.000Z';

test('a curator run, recognized by its first user message, is dropped and counted', () => {
  const world = makeWorld();
  world.write(PROJECT, 'round.jsonl', [customTitle(), user(`${SIGNATURE}\nWindow: 23/09/2026.`, INSIDE), assistant('reading', LATER)]);
  const human = world.write(PROJECT, 'ana.jsonl', [user('Ana asks about the budget', INSIDE)]);
  const plan = world.collect();
  assert.deepEqual(paths(plan), [human]);
  assert.equal(plan.dropped.selfTrace, 1);
  assert.match(plan.promptBlock, /1 transcripts? left out as the curator's own runs/);
});

test('a human session that quotes the signature later stays in', () => {
  const world = makeWorld();
  const quoting = world.write(PROJECT, 'ana.jsonl', [
    user('Ana wants to change the curator prompt', INSIDE),
    assistant(`The prompt starts with "${SIGNATURE}".`, LATER),
    user(`${SIGNATURE}: why does it start like this?`, LATER),
  ]);
  const plan = world.collect();
  assert.deepEqual(paths(plan), [quoting]);
  assert.equal(plan.dropped.selfTrace, 0);
});

test('a signature inside the first message, not at its start, does not drop the file', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'ana.jsonl', [user(`Ana pastes: "${SIGNATURE}" and asks what it is`, INSIDE)]);
  assert.deepEqual(paths(world.collect()), [file]);
});

test('meta lines and tool-result-only lines are passed over to find the first user message', () => {
  const world = makeWorld();
  world.write(PROJECT, 'round.jsonl', [
    meta('Caveat: the messages below were generated by the user', INSIDE),
    toolResult(INSIDE),
    userBlocks([{ type: 'text', text: `  ${SIGNATURE} round` }], LATER),
  ]);
  const human = world.write(PROJECT, 'ana.jsonl', [
    meta(`${SIGNATURE} appears in a meta line only`, INSIDE),
    user('Ana asks', LATER),
  ]);
  const plan = world.collect();
  assert.deepEqual(paths(plan), [human]);
  assert.equal(plan.dropped.selfTrace, 1);
});

test('an extra signature drops its own runs; a blank extra signature drops nothing', () => {
  const world = makeWorld({ extraSignatures: ['', '   ', 'Morning briefing'] });
  world.write(PROJECT, 'briefing.jsonl', [user('Morning briefing for Ana', INSIDE)]);
  const human = world.write(PROJECT, 'ana.jsonl', [user('Ana asks', INSIDE)]);
  const plan = world.collect();
  assert.deepEqual(paths(plan), [human]);
  assert.equal(plan.dropped.selfTrace, 1);
});

test('a file whose first user message is unparseable stays in rather than being guessed away', () => {
  const world = makeWorld();
  const file = world.write(PROJECT, 'ana.jsonl', [
    `{"type":"user","message":{"role":"user","content":"${SIGNATURE} cut`,
    user('Ana asks', INSIDE),
  ]);
  assert.deepEqual(paths(world.collect()), [file]);
});
